Repository Stnagam/Reitz-Union-Hotel-Management, pull requests merged in 2022-02, with the labels that each got.

#42 Sprint1
  package-lock.json
  package.json
  workspaces/client/package-lock.json
  workspaces/client/package.json
  workspaces/client/src/App.tsx
  workspaces/client/src/components/ReitzUnion.jpg
  workspaces/client/src/components/home.tsx
  workspaces/client/src/components/login.tsx
  workspaces/client/src/default/footer.tsx
  workspaces/client/src/default/header.tsx
  workspaces/client/src/index.tsx
  yarn.lock
Labels: UI

#58 Added SignupHandler along wth folder Structure closes #57
  .gitignore
  package.json
  workspaces/client/package-lock.json
  workspaces/client/package.json
  workspaces/client/src/components/home.js
  workspaces/client/src/components/login.js
  workspaces/client/src/images/ReitzUnion.jpg
  workspaces/client/yarn.lock
  workspaces/server/.env
  workspaces/server/go.mod
  workspaces/server/go.sum
  workspaces/server/handlers/ForgotPasswordHandler.go
  workspaces/server/handlers/LoginHandler.go
  workspaces/server/handlers/LogoutHandler.go
  workspaces/server/handlers/SignUpHandler.go
  workspaces/server/main.go
  workspaces/server/models/usermodels.go
  workspaces/server/package.json
  workspaces/server/routes/routes.go
  workspaces/server/utils/dbConnectionUtils.go
  workspaces/server/utils/jsonUtils.go
  workspaces/server/utils/tokenVerifier.go
  yarn.lock
Labels: Backend, backlog

#61 Updated login with JWT #60
  workspaces/server/.gitignore
  workspaces/server/handlers/LoginHandler.go
  workspaces/server/handlers/LogoutHandler.go
  workspaces/server/handlers/SignUpHandler.go
  workspaces/server/models/exception.go
  workspaces/server/routes/routes.go
  workspaces/server/utils/tokenVerifier.go
Labels: Backend, Sprint 2
