Repository Stnagam/Reitz-Union-Hotel-Management, pull requests merged in 2022-03, with the labels that each got.

#75 Resolved CORS issue #74
  workspaces/server/routes/routes.go
Labels: bug, Backend, Sprint 2

#76 Inital booking logic #70
  workspaces/server/constants/BookingConstants.go
  workspaces/server/go.mod
  workspaces/server/go.sum
  workspaces/server/handlers/SignUpHandler.go
  workspaces/server/handlers/bookingHandler.go
  workspaces/server/models/bookings.go
Labels: Backend, Sprint 2

#82 Implemented Hot Reload for Go Server #81
  workspaces/server/package.json
Labels: Backend, Sprint 2

#89 Bookings Page Final #88
  workspaces/server/constants/BookingConstants.go
  workspaces/server/go.mod
  workspaces/server/go.sum
  workspaces/server/handlers/bookingHandler.go
  workspaces/server/handlers/dummy.go
  workspaces/server/models/bookings.go
  workspaces/server/routes/routes.go
  workspaces/server/utils/dbConnectionUtils.go
  workspaces/server/utils/tokenVerifier.go
Labels: Backend, Sprint 2

#90 Booking + Payement
  workspaces/client/src/Pages/Booking.js
  workspaces/client/src/Pages/Payment.js
  workspaces/client/src/Style/payment.css
Labels: UI, Sprint 2

#98 Resolved bookings handler error
  workspaces/client/src/Pages/Booking.js
  workspaces/client/src/Pages/Payment.js
  workspaces/server/handlers/bookingHandler.go
  workspaces/server/routes/routes.go
Labels: bug, Backend, Sprint 2

#108 calling confirmation emails function
  workspaces/client/src/Pages/Booking.js
  workspaces/client/src/Pages/Payment.js
  workspaces/server/handlers/bookingHandler.go
  workspaces/server/models/bookings.go
Labels: enhancement, UI, Backend, Sprint 2

#109 Updated LogoutHandler with response
  workspaces/client/src/components/header_common.js
  workspaces/server/handlers/LogoutHandler.go
Labels: enhancement, Backend, Sprint 2

#110 Booking Handler Testing done
  workspaces/server/handlers/BookingHandler_test.go
Labels: Backend, Sprint 2, Unit Tests

#111 Testing LogoutHandler done
  workspaces/server/handlers/LogoutHandler_test.go
Labels: Backend, Sprint 2, Unit Tests

#114 sprint2 documentation
  Sprint2.md
Labels: documentation, Sprint 2

#119 Initial customer request Handler #118
  workspaces/server/handlers/CustomerReqs.go
  workspaces/server/models/requests.go
  workspaces/server/routes/routes.go
  workspaces/server/utils/dbConnectionUtils.go
Labels: Backend, Sprint 3

#121 Added initial various get Customer request APIs
  workspaces/server/handlers/getCustomerRequests.go
  workspaces/server/handlers/updateStatusOfCR.go
  workspaces/server/models/requests.go
  workspaces/server/routes/routes.go
Labels: Backend, Sprint 3

#124 Sheela25mar
  workspaces/server/handlers/ConfirmationEmailHandler.go
  workspaces/server/handlers/OTPGenerationHandler.go
Labels: enhancement, Backend, Sprint 3

#126 Logic to Request Status Changed to Assigned
  workspaces/server/handlers/updateStatusOfCR.go
  workspaces/server/routes/routes.go
Labels: Backend, Sprint 3

#128 Fixed status change bug
  workspaces/server/handlers/updateStatusOfCR.go
  workspaces/server/models/requests.go
  workspaces/server/routes/routes.go
Labels: bug, Backend, Sprint 3

#129 added Available room logic and updated booking room logic
  workspaces/server/go.mod
  workspaces/server/handlers/AvailableRoomsHandler.go
  workspaces/server/handlers/bookingHandler.go
  workspaces/server/models/bookings.go
  workspaces/server/models/roommodel.go
  workspaces/server/routes/routes.go
  workspaces/server/utils/dbConnectionUtils.go
Labels: Backend, Sprint 3

#134 Status change from Assigned to Completed
  workspaces/server/handlers/updateStatusOfCR.go
  workspaces/server/models/requests.go
Labels: bug, Backend, Sprint 3

#137 Fixed package lock deletion
  package-lock.json
  workspaces/server/go.sum
  yarn.lock
Labels: bug, Frontend, Sprint 3

#139 Delete Completed requests
  workspaces/server/handlers/UpdateStatusOfCR.go
  workspaces/server/models/requests.go
  workspaces/server/routes/routes.go
Labels: Backend, Sprint 3

#145 pkey issue w.r.t customer_requests
  workspaces/server/handlers/CustomerReqs.go
Labels: enhancement, Backend, Sprint 3
