Repository Stnagam/Reitz-Union-Hotel-Management, pull requests merged in 2022-04, with the labels that each got.

#155 Sprint3 tests
  workspaces/client/cypress/integration/1-getting-started/pending_to_assigned_test.js
Labels: UI, cypress, Sprint 3

#157 Checked for errors
  workspaces/server/handlers/CustomerReqs.go
  workspaces/server/handlers/UpdateStatusOfCR.go
  workspaces/server/handlers/getCustomerRequests.go
Labels: enhancement, Backend, Sprint 3

#165 Sprint3 tests
  workspaces/server/handlers/CustomerReqs_test.go
  workspaces/server/handlers/getCustomerRequests_test.go
Labels: Backend, Unit Tests, Sprint 3

#166 Hetansh-S3
  workspaces/client/src/Pages/CustomerHome.js
  workspaces/client/src/Pages/Payment.js
  workspaces/client/src/components/Request.js
  workspaces/client/src/components/Tile.js
Labels: UI

#163 rooms styling complete
  workspaces/client/cypress/integration/1-getting-started/Rooms_test.js
  workspaces/client/src/Pages/Rooms.js
  workspaces/client/src/Style/rooms.css
Labels: UI, cypress

#169 Test for Update CRs
  workspaces/server/handlers/UpdateStatusOfCRs_test.go
Labels: Backend, Unit Tests, Sprint 3

#170 Admin changes
  workspaces/client/src/Pages/Admin.js
  workspaces/client/src/Pages/AdminLogin.js
Labels: Frontend, Sprint 3

#173 sprint3 documentation
  Sprint3.md
Labels: documentation, Backend, Frontend, Sprint 3

#174 added demo link
  Sprint3.md
Labels: documentation, Backend, Frontend, Sprint 3

#178 Sheelaapr12
  workspaces/server/handlers/FeedbackHandler.go
  workspaces/server/models/feedbackmodel.go
  workspaces/server/routes/routes.go
  workspaces/server/utils/dbConnectionUtils.go
Labels: Backend, Sprint4

#186 Changes in profile and some common changes
  workspaces/client/package-lock.json
  workspaces/client/package.json
  workspaces/client/src/Pages/CustomerHome.js
  workspaces/client/src/Pages/Profile.js
  workspaces/client/src/Pages/Signup.js
  workspaces/client/src/Style/Login.css
  workspaces/client/src/Style/footer.css
  workspaces/client/src/Style/signup.css
  workspaces/client/src/components/Request.js
  workspaces/client/src/components/header_common.js
  workspaces/client/src/index.js
  workspaces/client/yarn.lock
Labels: UI, Frontend

#189 Styling for profile and dropdown menu
  workspaces/client/src/Style/profile.css
  workspaces/client/src/Style/userDropDown.css
  workspaces/client/src/components/UserDropDown.js
Labels: UI, Frontend

#190 service for get user details
  workspaces/server/handlers/UserProfile.go
  workspaces/server/routes/routes.go
Labels: Backend, Sprint4

#192 service for updating mobile number
  workspaces/server/handlers/UserProfile.go
  workspaces/server/routes/routes.go
Labels: Backend, Sprint4

#194 service for getbookings
  workspaces/server/handlers/GetBookings.go
  workspaces/server/routes/routes.go
Labels: Backend, Sprint4

#195 viewfeedback page
  workspaces/client/src/Pages/Viewfeedback.js
Labels: Frontend

#196 Admin page header, Dropdown for admin
  workspaces/client/src/Pages/Admin.js
  workspaces/client/src/Pages/Profile.js
  workspaces/client/src/components/AdminDropDown.js
  workspaces/client/src/components/Admin_Header_Common.js
Labels: Frontend

#198 userdropdown
  workspaces/client/src/components/UserDropDown.js
Labels: Frontend

#199 Cancel Booking/ Give Feedback / View Feedback routing
  workspaces/client/src/Pages/Admin.js
  workspaces/client/src/Pages/CustomerHome.js
  workspaces/client/src/index.js
Labels: Frontend

#200 Setting flow for user
  workspaces/client/src/Pages/Cancellation.js
  workspaces/client/src/Pages/CustomerHome.js
  workspaces/client/src/Pages/Getfeedback.js
  workspaces/client/src/Pages/Login.js
  workspaces/client/src/Pages/Profile.js
  workspaces/client/src/components/UserDropDown.js
  workspaces/client/src/components/header_common.js
  workspaces/client/src/index.js
Labels: Frontend

#201 Sheela20apr
  APIDocumentation.md
  workspaces/server/handlers/FeedbackHandler_test.go
Labels: Backend, Unit Tests, Sprint4

#204 cypress test for sprint 4
  workspaces/client/cypress/integration/1-getting-started/user_details_test.js
  workspaces/client/cypress/integration/1-getting-started/view_bookings.js
Labels: UI, Unit Tests, cypress, Sprint4

#206 Sprint 4 documentation
  Sprint4.md
Labels: documentation, UI, Backend, Sprint4

#207 Added 200 words description.
  Sprint4.md
Labels: documentation, Backend

#212 Unit test for get user details
  workspaces/server/handlers/GetBookings_test.go
  workspaces/server/handlers/UserDetails_test.go
Labels: Backend, Unit Tests, Sprint4

#214 unit test for get booking
  workspaces/server/handlers/GetBookings_test.go
Labels: Backend, Unit Tests, Sprint4
